# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NanoFfmpeg < Formula
  desc "A beautiful terminal UI for ffmpeg"
  homepage "https://github.com/dgr8akki/nano-ffmpeg"
  version "0.1.0"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.1.0/nano-ffmpeg_0.1.0_darwin_amd64.tar.gz"
      sha256 "0a3a897179e872c3188651ea17c190d631b556f9c054162ab617a681daf98dcb"

      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.1.0/nano-ffmpeg_0.1.0_darwin_arm64.tar.gz"
      sha256 "ae5f5dcb3d59d1e926e9f00697564d2558c92f206dce8d4396e1d468c14ba4a6"

      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.1.0/nano-ffmpeg_0.1.0_linux_amd64.tar.gz"
      sha256 "36631ba041ad02e0476d94422d1d60997067397d67d8c123920fcb156b44a096"
      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.1.0/nano-ffmpeg_0.1.0_linux_arm64.tar.gz"
      sha256 "6bb43dcea56fc54d5fa76a6250763c62d92e517e4ef252dd5f43163d1ff6f1e6"
      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
  end

  test do
    system "#{bin}/nano-ffmpeg", "--version"
  end
end
