# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NanoFfmpeg < Formula
  desc "A beautiful terminal UI for ffmpeg"
  homepage "https://github.com/dgr8akki/nano-ffmpeg"
  version "0.2.0"
  license "MIT"

  depends_on "ffmpeg-full"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.2.0/nano-ffmpeg_0.2.0_darwin_amd64.tar.gz"
      sha256 "797a808f77094e6b70dc8f0fc1289ea015ce421432f44a4de9a989bc116c96dc"

      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.2.0/nano-ffmpeg_0.2.0_darwin_arm64.tar.gz"
      sha256 "35bc2d05b41f53ab64aafb0ef615b12af468282952214d9173a44af725fb06a3"

      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.2.0/nano-ffmpeg_0.2.0_linux_amd64.tar.gz"
      sha256 "7dce0c262a21890bcdbe0efd1837a699ef4d7b98ca3e6efc739acd3ba00ff365"
      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgr8akki/nano-ffmpeg/releases/download/v0.2.0/nano-ffmpeg_0.2.0_linux_arm64.tar.gz"
      sha256 "918fc5fcea1be73792337deea9a4b27bbec1bfea9df3ed726513fd73eb25d2f3"
      define_method(:install) do
        bin.install "nano-ffmpeg"
      end
    end
  end

  test do
    system "#{bin}/nano-ffmpeg", "--version"
  end
end
